// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: administrators/administrators.proto

package administrators

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_administrators_administrators_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_administrators_administrators_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_administrators_administrators_proto_rawDescGZIP(), []int{0}
}

type CreateAdministratorRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId    string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Email             string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	DisplayName       string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	AuthorizationRole string                 `protobuf:"bytes,4,opt,name=authorization_role,json=authorizationRole,proto3" json:"authorization_role,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateAdministratorRequest) Reset() {
	*x = CreateAdministratorRequest{}
	mi := &file_administrators_administrators_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAdministratorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAdministratorRequest) ProtoMessage() {}

func (x *CreateAdministratorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_administrators_administrators_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAdministratorRequest.ProtoReflect.Descriptor instead.
func (*CreateAdministratorRequest) Descriptor() ([]byte, []int) {
	return file_administrators_administrators_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAdministratorRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *CreateAdministratorRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateAdministratorRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *CreateAdministratorRequest) GetAuthorizationRole() string {
	if x != nil {
		return x.AuthorizationRole
	}
	return ""
}

type ActivateAdministratorsRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Token            string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	VerificationCode string                 `protobuf:"bytes,2,opt,name=verification_code,json=verificationCode,proto3" json:"verification_code,omitempty"`
	Password         string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ActivateAdministratorsRequest) Reset() {
	*x = ActivateAdministratorsRequest{}
	mi := &file_administrators_administrators_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateAdministratorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateAdministratorsRequest) ProtoMessage() {}

func (x *ActivateAdministratorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_administrators_administrators_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateAdministratorsRequest.ProtoReflect.Descriptor instead.
func (*ActivateAdministratorsRequest) Descriptor() ([]byte, []int) {
	return file_administrators_administrators_proto_rawDescGZIP(), []int{2}
}

func (x *ActivateAdministratorsRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ActivateAdministratorsRequest) GetVerificationCode() string {
	if x != nil {
		return x.VerificationCode
	}
	return ""
}

func (x *ActivateAdministratorsRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type GetAdministratorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAdministratorRequest) Reset() {
	*x = GetAdministratorRequest{}
	mi := &file_administrators_administrators_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdministratorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdministratorRequest) ProtoMessage() {}

func (x *GetAdministratorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_administrators_administrators_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdministratorRequest.ProtoReflect.Descriptor instead.
func (*GetAdministratorRequest) Descriptor() ([]byte, []int) {
	return file_administrators_administrators_proto_rawDescGZIP(), []int{3}
}

func (x *GetAdministratorRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListAdministratorsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListAdministratorsRequest) Reset() {
	*x = ListAdministratorsRequest{}
	mi := &file_administrators_administrators_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAdministratorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdministratorsRequest) ProtoMessage() {}

func (x *ListAdministratorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_administrators_administrators_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdministratorsRequest.ProtoReflect.Descriptor instead.
func (*ListAdministratorsRequest) Descriptor() ([]byte, []int) {
	return file_administrators_administrators_proto_rawDescGZIP(), []int{4}
}

func (x *ListAdministratorsRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

type UpdateAdministratorRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email             string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	AuthorizationRole string                 `protobuf:"bytes,3,opt,name=authorization_role,json=authorizationRole,proto3" json:"authorization_role,omitempty"`
	DisplayName       string                 `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateAdministratorRequest) Reset() {
	*x = UpdateAdministratorRequest{}
	mi := &file_administrators_administrators_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAdministratorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAdministratorRequest) ProtoMessage() {}

func (x *UpdateAdministratorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_administrators_administrators_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAdministratorRequest.ProtoReflect.Descriptor instead.
func (*UpdateAdministratorRequest) Descriptor() ([]byte, []int) {
	return file_administrators_administrators_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateAdministratorRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateAdministratorRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateAdministratorRequest) GetAuthorizationRole() string {
	if x != nil {
		return x.AuthorizationRole
	}
	return ""
}

func (x *UpdateAdministratorRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

type DeleteAdministratorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAdministratorRequest) Reset() {
	*x = DeleteAdministratorRequest{}
	mi := &file_administrators_administrators_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAdministratorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAdministratorRequest) ProtoMessage() {}

func (x *DeleteAdministratorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_administrators_administrators_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAdministratorRequest.ProtoReflect.Descriptor instead.
func (*DeleteAdministratorRequest) Descriptor() ([]byte, []int) {
	return file_administrators_administrators_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteAdministratorRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAdministratorResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email             string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	DisplayName       string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	OrganizationId    string                 `protobuf:"bytes,4,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Verified          bool                   `protobuf:"varint,5,opt,name=verified,proto3" json:"verified,omitempty"`
	AuthorizationRole string                 `protobuf:"bytes,6,opt,name=authorization_role,json=authorizationRole,proto3" json:"authorization_role,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetAdministratorResponse) Reset() {
	*x = GetAdministratorResponse{}
	mi := &file_administrators_administrators_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdministratorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdministratorResponse) ProtoMessage() {}

func (x *GetAdministratorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_administrators_administrators_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdministratorResponse.ProtoReflect.Descriptor instead.
func (*GetAdministratorResponse) Descriptor() ([]byte, []int) {
	return file_administrators_administrators_proto_rawDescGZIP(), []int{7}
}

func (x *GetAdministratorResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetAdministratorResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetAdministratorResponse) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *GetAdministratorResponse) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *GetAdministratorResponse) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *GetAdministratorResponse) GetAuthorizationRole() string {
	if x != nil {
		return x.AuthorizationRole
	}
	return ""
}

type ListAdministratorsResponse struct {
	state          protoimpl.MessageState      `protogen:"open.v1"`
	Administrators []*GetAdministratorResponse `protobuf:"bytes,1,rep,name=administrators,proto3" json:"administrators,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListAdministratorsResponse) Reset() {
	*x = ListAdministratorsResponse{}
	mi := &file_administrators_administrators_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAdministratorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdministratorsResponse) ProtoMessage() {}

func (x *ListAdministratorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_administrators_administrators_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdministratorsResponse.ProtoReflect.Descriptor instead.
func (*ListAdministratorsResponse) Descriptor() ([]byte, []int) {
	return file_administrators_administrators_proto_rawDescGZIP(), []int{8}
}

func (x *ListAdministratorsResponse) GetAdministrators() []*GetAdministratorResponse {
	if x != nil {
		return x.Administrators
	}
	return nil
}

var File_administrators_administrators_proto protoreflect.FileDescriptor

const file_administrators_administrators_proto_rawDesc = "" +
	"\n" +
	"#administrators/administrators.proto\x12\x0eadministrators\x1a\x1cgoogle/api/annotations.proto\"\a\n" +
	"\x05Empty\"\xad\x01\n" +
	"\x1aCreateAdministratorRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12-\n" +
	"\x12authorization_role\x18\x04 \x01(\tR\x11authorizationRole\"~\n" +
	"\x1dActivateAdministratorsRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12+\n" +
	"\x11verification_code\x18\x02 \x01(\tR\x10verificationCode\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\")\n" +
	"\x17GetAdministratorRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"D\n" +
	"\x19ListAdministratorsRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\"\x94\x01\n" +
	"\x1aUpdateAdministratorRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12-\n" +
	"\x12authorization_role\x18\x03 \x01(\tR\x11authorizationRole\x12!\n" +
	"\fdisplay_name\x18\x04 \x01(\tR\vdisplayName\",\n" +
	"\x1aDeleteAdministratorRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xd7\x01\n" +
	"\x18GetAdministratorResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12'\n" +
	"\x0forganization_id\x18\x04 \x01(\tR\x0eorganizationId\x12\x1a\n" +
	"\bverified\x18\x05 \x01(\bR\bverified\x12-\n" +
	"\x12authorization_role\x18\x06 \x01(\tR\x11authorizationRole\"n\n" +
	"\x1aListAdministratorsResponse\x12P\n" +
	"\x0eadministrators\x18\x01 \x03(\v2(.administrators.GetAdministratorResponseR\x0eadministrators2\xc3\x05\n" +
	"\x15AdministratorsService\x12j\n" +
	"\x06Create\x12*.administrators.CreateAdministratorRequest\x1a\x15.administrators.Empty\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/administrators\x12i\n" +
	"\bActivate\x12-.administrators.ActivateAdministratorsRequest\x1a\x15.administrators.Empty\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/activate\x12y\n" +
	"\x03Get\x12'.administrators.GetAdministratorRequest\x1a(.administrators.GetAdministratorResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/v1/administrators/{id}\x12y\n" +
	"\x04List\x12).administrators.ListAdministratorsRequest\x1a*.administrators.ListAdministratorsResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/administrators\x12o\n" +
	"\x06Update\x12*.administrators.UpdateAdministratorRequest\x1a\x15.administrators.Empty\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\x1a\x17/v1/administrators/{id}\x12l\n" +
	"\x06Delete\x12*.administrators.DeleteAdministratorRequest\x1a\x15.administrators.Empty\"\x1f\x82\xd3\xe4\x93\x02\x19*\x17/v1/administrators/{id}BIZGgithub.com/danielhoward314/packet-sentry/protogen/golang/administratorsb\x06proto3"

var (
	file_administrators_administrators_proto_rawDescOnce sync.Once
	file_administrators_administrators_proto_rawDescData []byte
)

func file_administrators_administrators_proto_rawDescGZIP() []byte {
	file_administrators_administrators_proto_rawDescOnce.Do(func() {
		file_administrators_administrators_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_administrators_administrators_proto_rawDesc), len(file_administrators_administrators_proto_rawDesc)))
	})
	return file_administrators_administrators_proto_rawDescData
}

var file_administrators_administrators_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_administrators_administrators_proto_goTypes = []any{
	(*Empty)(nil),                         // 0: administrators.Empty
	(*CreateAdministratorRequest)(nil),    // 1: administrators.CreateAdministratorRequest
	(*ActivateAdministratorsRequest)(nil), // 2: administrators.ActivateAdministratorsRequest
	(*GetAdministratorRequest)(nil),       // 3: administrators.GetAdministratorRequest
	(*ListAdministratorsRequest)(nil),     // 4: administrators.ListAdministratorsRequest
	(*UpdateAdministratorRequest)(nil),    // 5: administrators.UpdateAdministratorRequest
	(*DeleteAdministratorRequest)(nil),    // 6: administrators.DeleteAdministratorRequest
	(*GetAdministratorResponse)(nil),      // 7: administrators.GetAdministratorResponse
	(*ListAdministratorsResponse)(nil),    // 8: administrators.ListAdministratorsResponse
}
var file_administrators_administrators_proto_depIdxs = []int32{
	7, // 0: administrators.ListAdministratorsResponse.administrators:type_name -> administrators.GetAdministratorResponse
	1, // 1: administrators.AdministratorsService.Create:input_type -> administrators.CreateAdministratorRequest
	2, // 2: administrators.AdministratorsService.Activate:input_type -> administrators.ActivateAdministratorsRequest
	3, // 3: administrators.AdministratorsService.Get:input_type -> administrators.GetAdministratorRequest
	4, // 4: administrators.AdministratorsService.List:input_type -> administrators.ListAdministratorsRequest
	5, // 5: administrators.AdministratorsService.Update:input_type -> administrators.UpdateAdministratorRequest
	6, // 6: administrators.AdministratorsService.Delete:input_type -> administrators.DeleteAdministratorRequest
	0, // 7: administrators.AdministratorsService.Create:output_type -> administrators.Empty
	0, // 8: administrators.AdministratorsService.Activate:output_type -> administrators.Empty
	7, // 9: administrators.AdministratorsService.Get:output_type -> administrators.GetAdministratorResponse
	8, // 10: administrators.AdministratorsService.List:output_type -> administrators.ListAdministratorsResponse
	0, // 11: administrators.AdministratorsService.Update:output_type -> administrators.Empty
	0, // 12: administrators.AdministratorsService.Delete:output_type -> administrators.Empty
	7, // [7:13] is the sub-list for method output_type
	1, // [1:7] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_administrators_administrators_proto_init() }
func file_administrators_administrators_proto_init() {
	if File_administrators_administrators_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_administrators_administrators_proto_rawDesc), len(file_administrators_administrators_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_administrators_administrators_proto_goTypes,
		DependencyIndexes: file_administrators_administrators_proto_depIdxs,
		MessageInfos:      file_administrators_administrators_proto_msgTypes,
	}.Build()
	File_administrators_administrators_proto = out.File
	file_administrators_administrators_proto_goTypes = nil
	file_administrators_administrators_proto_depIdxs = nil
}
