// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: devices/devices.proto

package devices

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_devices_devices_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_devices_devices_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_devices_devices_proto_rawDescGZIP(), []int{0}
}

type GetDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceRequest) Reset() {
	*x = GetDeviceRequest{}
	mi := &file_devices_devices_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceRequest) ProtoMessage() {}

func (x *GetDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_devices_devices_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceRequest.ProtoReflect.Descriptor instead.
func (*GetDeviceRequest) Descriptor() ([]byte, []int) {
	return file_devices_devices_proto_rawDescGZIP(), []int{1}
}

func (x *GetDeviceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListDevicesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListDevicesRequest) Reset() {
	*x = ListDevicesRequest{}
	mi := &file_devices_devices_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesRequest) ProtoMessage() {}

func (x *ListDevicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_devices_devices_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesRequest.ProtoReflect.Descriptor instead.
func (*ListDevicesRequest) Descriptor() ([]byte, []int) {
	return file_devices_devices_proto_rawDescGZIP(), []int{2}
}

func (x *ListDevicesRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

type UpdateDeviceRequest struct {
	state                    protoimpl.MessageState                `protogen:"open.v1"`
	Id                       string                                `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PcapVersion              string                                `protobuf:"bytes,2,opt,name=pcap_version,json=pcapVersion,proto3" json:"pcap_version,omitempty"`
	Interfaces               []string                              `protobuf:"bytes,3,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
	ClientCertPem            string                                `protobuf:"bytes,4,opt,name=client_cert_pem,json=clientCertPem,proto3" json:"client_cert_pem,omitempty"`
	ClientCertFingerprint    string                                `protobuf:"bytes,5,opt,name=client_cert_fingerprint,json=clientCertFingerprint,proto3" json:"client_cert_fingerprint,omitempty"`
	InterfaceBpfAssociations map[string]*InterfaceCaptureMapUpdate `protobuf:"bytes,6,rep,name=interface_bpf_associations,json=interfaceBpfAssociations,proto3" json:"interface_bpf_associations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *UpdateDeviceRequest) Reset() {
	*x = UpdateDeviceRequest{}
	mi := &file_devices_devices_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDeviceRequest) ProtoMessage() {}

func (x *UpdateDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_devices_devices_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDeviceRequest.ProtoReflect.Descriptor instead.
func (*UpdateDeviceRequest) Descriptor() ([]byte, []int) {
	return file_devices_devices_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateDeviceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateDeviceRequest) GetPcapVersion() string {
	if x != nil {
		return x.PcapVersion
	}
	return ""
}

func (x *UpdateDeviceRequest) GetInterfaces() []string {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

func (x *UpdateDeviceRequest) GetClientCertPem() string {
	if x != nil {
		return x.ClientCertPem
	}
	return ""
}

func (x *UpdateDeviceRequest) GetClientCertFingerprint() string {
	if x != nil {
		return x.ClientCertFingerprint
	}
	return ""
}

func (x *UpdateDeviceRequest) GetInterfaceBpfAssociations() map[string]*InterfaceCaptureMapUpdate {
	if x != nil {
		return x.InterfaceBpfAssociations
	}
	return nil
}

type CaptureConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bpf           string                 `protobuf:"bytes,1,opt,name=bpf,proto3" json:"bpf,omitempty"`
	DeviceName    string                 `protobuf:"bytes,2,opt,name=deviceName,proto3" json:"deviceName,omitempty"`
	Promiscuous   bool                   `protobuf:"varint,3,opt,name=promiscuous,proto3" json:"promiscuous,omitempty"`
	SnapLen       int32                  `protobuf:"varint,4,opt,name=snapLen,proto3" json:"snapLen,omitempty"`
	Timeout       int64                  `protobuf:"varint,5,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaptureConfig) Reset() {
	*x = CaptureConfig{}
	mi := &file_devices_devices_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureConfig) ProtoMessage() {}

func (x *CaptureConfig) ProtoReflect() protoreflect.Message {
	mi := &file_devices_devices_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureConfig.ProtoReflect.Descriptor instead.
func (*CaptureConfig) Descriptor() ([]byte, []int) {
	return file_devices_devices_proto_rawDescGZIP(), []int{4}
}

func (x *CaptureConfig) GetBpf() string {
	if x != nil {
		return x.Bpf
	}
	return ""
}

func (x *CaptureConfig) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *CaptureConfig) GetPromiscuous() bool {
	if x != nil {
		return x.Promiscuous
	}
	return false
}

func (x *CaptureConfig) GetSnapLen() int32 {
	if x != nil {
		return x.SnapLen
	}
	return 0
}

func (x *CaptureConfig) GetTimeout() int64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

type InterfaceCaptureMap struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Captures      map[uint64]*CaptureConfig `protobuf:"bytes,1,rep,name=captures,proto3" json:"captures,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterfaceCaptureMap) Reset() {
	*x = InterfaceCaptureMap{}
	mi := &file_devices_devices_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterfaceCaptureMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfaceCaptureMap) ProtoMessage() {}

func (x *InterfaceCaptureMap) ProtoReflect() protoreflect.Message {
	mi := &file_devices_devices_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterfaceCaptureMap.ProtoReflect.Descriptor instead.
func (*InterfaceCaptureMap) Descriptor() ([]byte, []int) {
	return file_devices_devices_proto_rawDescGZIP(), []int{5}
}

func (x *InterfaceCaptureMap) GetCaptures() map[uint64]*CaptureConfig {
	if x != nil {
		return x.Captures
	}
	return nil
}

type InterfaceCaptureMapUpdate struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Captures      map[string]*CaptureConfig `protobuf:"bytes,1,rep,name=captures,proto3" json:"captures,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterfaceCaptureMapUpdate) Reset() {
	*x = InterfaceCaptureMapUpdate{}
	mi := &file_devices_devices_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterfaceCaptureMapUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfaceCaptureMapUpdate) ProtoMessage() {}

func (x *InterfaceCaptureMapUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_devices_devices_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterfaceCaptureMapUpdate.ProtoReflect.Descriptor instead.
func (*InterfaceCaptureMapUpdate) Descriptor() ([]byte, []int) {
	return file_devices_devices_proto_rawDescGZIP(), []int{6}
}

func (x *InterfaceCaptureMapUpdate) GetCaptures() map[string]*CaptureConfig {
	if x != nil {
		return x.Captures
	}
	return nil
}

type GetDeviceResponse struct {
	state                    protoimpl.MessageState          `protogen:"open.v1"`
	Id                       string                          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrganizationId           string                          `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	OsUniqueIdentifier       string                          `protobuf:"bytes,3,opt,name=os_unique_identifier,json=osUniqueIdentifier,proto3" json:"os_unique_identifier,omitempty"`
	ClientCertPem            string                          `protobuf:"bytes,4,opt,name=client_cert_pem,json=clientCertPem,proto3" json:"client_cert_pem,omitempty"`
	ClientCertFingerprint    string                          `protobuf:"bytes,5,opt,name=client_cert_fingerprint,json=clientCertFingerprint,proto3" json:"client_cert_fingerprint,omitempty"`
	InterfaceBpfAssociations map[string]*InterfaceCaptureMap `protobuf:"bytes,6,rep,name=interface_bpf_associations,json=interfaceBpfAssociations,proto3" json:"interface_bpf_associations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	PreviousAssociations     map[string]*InterfaceCaptureMap `protobuf:"bytes,7,rep,name=previous_associations,json=previousAssociations,proto3" json:"previous_associations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	PcapVersion              string                          `protobuf:"bytes,8,opt,name=pcap_version,json=pcapVersion,proto3" json:"pcap_version,omitempty"`
	Interfaces               []string                        `protobuf:"bytes,9,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *GetDeviceResponse) Reset() {
	*x = GetDeviceResponse{}
	mi := &file_devices_devices_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceResponse) ProtoMessage() {}

func (x *GetDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_devices_devices_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceResponse.ProtoReflect.Descriptor instead.
func (*GetDeviceResponse) Descriptor() ([]byte, []int) {
	return file_devices_devices_proto_rawDescGZIP(), []int{7}
}

func (x *GetDeviceResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetDeviceResponse) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *GetDeviceResponse) GetOsUniqueIdentifier() string {
	if x != nil {
		return x.OsUniqueIdentifier
	}
	return ""
}

func (x *GetDeviceResponse) GetClientCertPem() string {
	if x != nil {
		return x.ClientCertPem
	}
	return ""
}

func (x *GetDeviceResponse) GetClientCertFingerprint() string {
	if x != nil {
		return x.ClientCertFingerprint
	}
	return ""
}

func (x *GetDeviceResponse) GetInterfaceBpfAssociations() map[string]*InterfaceCaptureMap {
	if x != nil {
		return x.InterfaceBpfAssociations
	}
	return nil
}

func (x *GetDeviceResponse) GetPreviousAssociations() map[string]*InterfaceCaptureMap {
	if x != nil {
		return x.PreviousAssociations
	}
	return nil
}

func (x *GetDeviceResponse) GetPcapVersion() string {
	if x != nil {
		return x.PcapVersion
	}
	return ""
}

func (x *GetDeviceResponse) GetInterfaces() []string {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

type ListDevicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*GetDeviceResponse   `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesResponse) Reset() {
	*x = ListDevicesResponse{}
	mi := &file_devices_devices_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesResponse) ProtoMessage() {}

func (x *ListDevicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_devices_devices_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesResponse.ProtoReflect.Descriptor instead.
func (*ListDevicesResponse) Descriptor() ([]byte, []int) {
	return file_devices_devices_proto_rawDescGZIP(), []int{8}
}

func (x *ListDevicesResponse) GetDevices() []*GetDeviceResponse {
	if x != nil {
		return x.Devices
	}
	return nil
}

var File_devices_devices_proto protoreflect.FileDescriptor

const file_devices_devices_proto_rawDesc = "" +
	"\n" +
	"\x15devices/devices.proto\x12\adevices\x1a\x1cgoogle/api/annotations.proto\"\a\n" +
	"\x05Empty\"\"\n" +
	"\x10GetDeviceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"=\n" +
	"\x12ListDevicesRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\"\xb3\x03\n" +
	"\x13UpdateDeviceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fpcap_version\x18\x02 \x01(\tR\vpcapVersion\x12\x1e\n" +
	"\n" +
	"interfaces\x18\x03 \x03(\tR\n" +
	"interfaces\x12&\n" +
	"\x0fclient_cert_pem\x18\x04 \x01(\tR\rclientCertPem\x126\n" +
	"\x17client_cert_fingerprint\x18\x05 \x01(\tR\x15clientCertFingerprint\x12x\n" +
	"\x1ainterface_bpf_associations\x18\x06 \x03(\v2:.devices.UpdateDeviceRequest.InterfaceBpfAssociationsEntryR\x18interfaceBpfAssociations\x1ao\n" +
	"\x1dInterfaceBpfAssociationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x128\n" +
	"\x05value\x18\x02 \x01(\v2\".devices.InterfaceCaptureMapUpdateR\x05value:\x028\x01\"\x97\x01\n" +
	"\rCaptureConfig\x12\x10\n" +
	"\x03bpf\x18\x01 \x01(\tR\x03bpf\x12\x1e\n" +
	"\n" +
	"deviceName\x18\x02 \x01(\tR\n" +
	"deviceName\x12 \n" +
	"\vpromiscuous\x18\x03 \x01(\bR\vpromiscuous\x12\x18\n" +
	"\asnapLen\x18\x04 \x01(\x05R\asnapLen\x12\x18\n" +
	"\atimeout\x18\x05 \x01(\x03R\atimeout\"\xb2\x01\n" +
	"\x13InterfaceCaptureMap\x12F\n" +
	"\bcaptures\x18\x01 \x03(\v2*.devices.InterfaceCaptureMap.CapturesEntryR\bcaptures\x1aS\n" +
	"\rCapturesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.devices.CaptureConfigR\x05value:\x028\x01\"\xbe\x01\n" +
	"\x19InterfaceCaptureMapUpdate\x12L\n" +
	"\bcaptures\x18\x01 \x03(\v20.devices.InterfaceCaptureMapUpdate.CapturesEntryR\bcaptures\x1aS\n" +
	"\rCapturesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.devices.CaptureConfigR\x05value:\x028\x01\"\xd6\x05\n" +
	"\x11GetDeviceResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x120\n" +
	"\x14os_unique_identifier\x18\x03 \x01(\tR\x12osUniqueIdentifier\x12&\n" +
	"\x0fclient_cert_pem\x18\x04 \x01(\tR\rclientCertPem\x126\n" +
	"\x17client_cert_fingerprint\x18\x05 \x01(\tR\x15clientCertFingerprint\x12v\n" +
	"\x1ainterface_bpf_associations\x18\x06 \x03(\v28.devices.GetDeviceResponse.InterfaceBpfAssociationsEntryR\x18interfaceBpfAssociations\x12i\n" +
	"\x15previous_associations\x18\a \x03(\v24.devices.GetDeviceResponse.PreviousAssociationsEntryR\x14previousAssociations\x12!\n" +
	"\fpcap_version\x18\b \x01(\tR\vpcapVersion\x12\x1e\n" +
	"\n" +
	"interfaces\x18\t \x03(\tR\n" +
	"interfaces\x1ai\n" +
	"\x1dInterfaceBpfAssociationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.devices.InterfaceCaptureMapR\x05value:\x028\x01\x1ae\n" +
	"\x19PreviousAssociationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.devices.InterfaceCaptureMapR\x05value:\x028\x01\"K\n" +
	"\x13ListDevicesResponse\x124\n" +
	"\adevices\x18\x01 \x03(\v2\x1a.devices.GetDeviceResponseR\adevices2\x95\x02\n" +
	"\x0eDevicesService\x12V\n" +
	"\x03Get\x12\x19.devices.GetDeviceRequest\x1a\x1a.devices.GetDeviceResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/devices/{id}\x12V\n" +
	"\x04List\x12\x1b.devices.ListDevicesRequest\x1a\x1c.devices.ListDevicesResponse\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/v1/devices\x12S\n" +
	"\x06Update\x12\x1c.devices.UpdateDeviceRequest\x1a\x0e.devices.Empty\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\x1a\x10/v1/devices/{id}BBZ@github.com/danielhoward314/packet-sentry/protogen/golang/devicesb\x06proto3"

var (
	file_devices_devices_proto_rawDescOnce sync.Once
	file_devices_devices_proto_rawDescData []byte
)

func file_devices_devices_proto_rawDescGZIP() []byte {
	file_devices_devices_proto_rawDescOnce.Do(func() {
		file_devices_devices_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_devices_devices_proto_rawDesc), len(file_devices_devices_proto_rawDesc)))
	})
	return file_devices_devices_proto_rawDescData
}

var file_devices_devices_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_devices_devices_proto_goTypes = []any{
	(*Empty)(nil),                     // 0: devices.Empty
	(*GetDeviceRequest)(nil),          // 1: devices.GetDeviceRequest
	(*ListDevicesRequest)(nil),        // 2: devices.ListDevicesRequest
	(*UpdateDeviceRequest)(nil),       // 3: devices.UpdateDeviceRequest
	(*CaptureConfig)(nil),             // 4: devices.CaptureConfig
	(*InterfaceCaptureMap)(nil),       // 5: devices.InterfaceCaptureMap
	(*InterfaceCaptureMapUpdate)(nil), // 6: devices.InterfaceCaptureMapUpdate
	(*GetDeviceResponse)(nil),         // 7: devices.GetDeviceResponse
	(*ListDevicesResponse)(nil),       // 8: devices.ListDevicesResponse
	nil,                               // 9: devices.UpdateDeviceRequest.InterfaceBpfAssociationsEntry
	nil,                               // 10: devices.InterfaceCaptureMap.CapturesEntry
	nil,                               // 11: devices.InterfaceCaptureMapUpdate.CapturesEntry
	nil,                               // 12: devices.GetDeviceResponse.InterfaceBpfAssociationsEntry
	nil,                               // 13: devices.GetDeviceResponse.PreviousAssociationsEntry
}
var file_devices_devices_proto_depIdxs = []int32{
	9,  // 0: devices.UpdateDeviceRequest.interface_bpf_associations:type_name -> devices.UpdateDeviceRequest.InterfaceBpfAssociationsEntry
	10, // 1: devices.InterfaceCaptureMap.captures:type_name -> devices.InterfaceCaptureMap.CapturesEntry
	11, // 2: devices.InterfaceCaptureMapUpdate.captures:type_name -> devices.InterfaceCaptureMapUpdate.CapturesEntry
	12, // 3: devices.GetDeviceResponse.interface_bpf_associations:type_name -> devices.GetDeviceResponse.InterfaceBpfAssociationsEntry
	13, // 4: devices.GetDeviceResponse.previous_associations:type_name -> devices.GetDeviceResponse.PreviousAssociationsEntry
	7,  // 5: devices.ListDevicesResponse.devices:type_name -> devices.GetDeviceResponse
	6,  // 6: devices.UpdateDeviceRequest.InterfaceBpfAssociationsEntry.value:type_name -> devices.InterfaceCaptureMapUpdate
	4,  // 7: devices.InterfaceCaptureMap.CapturesEntry.value:type_name -> devices.CaptureConfig
	4,  // 8: devices.InterfaceCaptureMapUpdate.CapturesEntry.value:type_name -> devices.CaptureConfig
	5,  // 9: devices.GetDeviceResponse.InterfaceBpfAssociationsEntry.value:type_name -> devices.InterfaceCaptureMap
	5,  // 10: devices.GetDeviceResponse.PreviousAssociationsEntry.value:type_name -> devices.InterfaceCaptureMap
	1,  // 11: devices.DevicesService.Get:input_type -> devices.GetDeviceRequest
	2,  // 12: devices.DevicesService.List:input_type -> devices.ListDevicesRequest
	3,  // 13: devices.DevicesService.Update:input_type -> devices.UpdateDeviceRequest
	7,  // 14: devices.DevicesService.Get:output_type -> devices.GetDeviceResponse
	8,  // 15: devices.DevicesService.List:output_type -> devices.ListDevicesResponse
	0,  // 16: devices.DevicesService.Update:output_type -> devices.Empty
	14, // [14:17] is the sub-list for method output_type
	11, // [11:14] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_devices_devices_proto_init() }
func file_devices_devices_proto_init() {
	if File_devices_devices_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_devices_devices_proto_rawDesc), len(file_devices_devices_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_devices_devices_proto_goTypes,
		DependencyIndexes: file_devices_devices_proto_depIdxs,
		MessageInfos:      file_devices_devices_proto_msgTypes,
	}.Build()
	File_devices_devices_proto = out.File
	file_devices_devices_proto_goTypes = nil
	file_devices_devices_proto_depIdxs = nil
}
