// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: organizations/organizations.proto

package organizations

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetOrganizationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrganizationRequest) Reset() {
	*x = GetOrganizationRequest{}
	mi := &file_organizations_organizations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrganizationRequest) ProtoMessage() {}

func (x *GetOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_organizations_organizations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrganizationRequest.ProtoReflect.Descriptor instead.
func (*GetOrganizationRequest) Descriptor() ([]byte, []int) {
	return file_organizations_organizations_proto_rawDescGZIP(), []int{0}
}

func (x *GetOrganizationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetOrganizationResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrganizationName string                 `protobuf:"bytes,2,opt,name=organization_name,json=organizationName,proto3" json:"organization_name,omitempty"`
	BillingPlan      string                 `protobuf:"bytes,3,opt,name=billing_plan,json=billingPlan,proto3" json:"billing_plan,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetOrganizationResponse) Reset() {
	*x = GetOrganizationResponse{}
	mi := &file_organizations_organizations_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrganizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrganizationResponse) ProtoMessage() {}

func (x *GetOrganizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_organizations_organizations_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrganizationResponse.ProtoReflect.Descriptor instead.
func (*GetOrganizationResponse) Descriptor() ([]byte, []int) {
	return file_organizations_organizations_proto_rawDescGZIP(), []int{1}
}

func (x *GetOrganizationResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetOrganizationResponse) GetOrganizationName() string {
	if x != nil {
		return x.OrganizationName
	}
	return ""
}

func (x *GetOrganizationResponse) GetBillingPlan() string {
	if x != nil {
		return x.BillingPlan
	}
	return ""
}

var File_organizations_organizations_proto protoreflect.FileDescriptor

const file_organizations_organizations_proto_rawDesc = "" +
	"\n" +
	"!organizations/organizations.proto\x12\rorganizations\x1a\x1cgoogle/api/annotations.proto\"(\n" +
	"\x16GetOrganizationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"y\n" +
	"\x17GetOrganizationResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12+\n" +
	"\x11organization_name\x18\x02 \x01(\tR\x10organizationName\x12!\n" +
	"\fbilling_plan\x18\x03 \x01(\tR\vbillingPlan2\x8c\x01\n" +
	"\x14OrganizationsService\x12t\n" +
	"\x03Get\x12%.organizations.GetOrganizationRequest\x1a&.organizations.GetOrganizationResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/v1/organizations/{id}BHZFgithub.com/danielhoward314/packet-sentry/protogen/golang/organizationsb\x06proto3"

var (
	file_organizations_organizations_proto_rawDescOnce sync.Once
	file_organizations_organizations_proto_rawDescData []byte
)

func file_organizations_organizations_proto_rawDescGZIP() []byte {
	file_organizations_organizations_proto_rawDescOnce.Do(func() {
		file_organizations_organizations_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_organizations_organizations_proto_rawDesc), len(file_organizations_organizations_proto_rawDesc)))
	})
	return file_organizations_organizations_proto_rawDescData
}

var file_organizations_organizations_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_organizations_organizations_proto_goTypes = []any{
	(*GetOrganizationRequest)(nil),  // 0: organizations.GetOrganizationRequest
	(*GetOrganizationResponse)(nil), // 1: organizations.GetOrganizationResponse
}
var file_organizations_organizations_proto_depIdxs = []int32{
	0, // 0: organizations.OrganizationsService.Get:input_type -> organizations.GetOrganizationRequest
	1, // 1: organizations.OrganizationsService.Get:output_type -> organizations.GetOrganizationResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_organizations_organizations_proto_init() }
func file_organizations_organizations_proto_init() {
	if File_organizations_organizations_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_organizations_organizations_proto_rawDesc), len(file_organizations_organizations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_organizations_organizations_proto_goTypes,
		DependencyIndexes: file_organizations_organizations_proto_depIdxs,
		MessageInfos:      file_organizations_organizations_proto_msgTypes,
	}.Build()
	File_organizations_organizations_proto = out.File
	file_organizations_organizations_proto_goTypes = nil
	file_organizations_organizations_proto_depIdxs = nil
}
