// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package agent

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentServiceClient interface {
	ReportInterfaces(ctx context.Context, in *ReportInterfacesRequest, opts ...grpc.CallOption) (*Empty, error)
	SendPacketEvent(ctx context.Context, opts ...grpc.CallOption) (AgentService_SendPacketEventClient, error)
	PollCommand(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Command, error)
	GetBPFConfig(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BPFConfig, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) ReportInterfaces(ctx context.Context, in *ReportInterfacesRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/agent.AgentService/ReportInterfaces", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) SendPacketEvent(ctx context.Context, opts ...grpc.CallOption) (AgentService_SendPacketEventClient, error) {
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[0], "/agent.AgentService/SendPacketEvent", opts...)
	if err != nil {
		return nil, err
	}
	x := &agentServiceSendPacketEventClient{stream}
	return x, nil
}

type AgentService_SendPacketEventClient interface {
	Send(*PacketEvent) error
	CloseAndRecv() (*Empty, error)
	grpc.ClientStream
}

type agentServiceSendPacketEventClient struct {
	grpc.ClientStream
}

func (x *agentServiceSendPacketEventClient) Send(m *PacketEvent) error {
	return x.ClientStream.SendMsg(m)
}

func (x *agentServiceSendPacketEventClient) CloseAndRecv() (*Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *agentServiceClient) PollCommand(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Command, error) {
	out := new(Command)
	err := c.cc.Invoke(ctx, "/agent.AgentService/PollCommand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetBPFConfig(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BPFConfig, error) {
	out := new(BPFConfig)
	err := c.cc.Invoke(ctx, "/agent.AgentService/GetBPFConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility
type AgentServiceServer interface {
	ReportInterfaces(context.Context, *ReportInterfacesRequest) (*Empty, error)
	SendPacketEvent(AgentService_SendPacketEventServer) error
	PollCommand(context.Context, *Empty) (*Command, error)
	GetBPFConfig(context.Context, *Empty) (*BPFConfig, error)
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAgentServiceServer struct {
}

func (UnimplementedAgentServiceServer) ReportInterfaces(context.Context, *ReportInterfacesRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportInterfaces not implemented")
}
func (UnimplementedAgentServiceServer) SendPacketEvent(AgentService_SendPacketEventServer) error {
	return status.Errorf(codes.Unimplemented, "method SendPacketEvent not implemented")
}
func (UnimplementedAgentServiceServer) PollCommand(context.Context, *Empty) (*Command, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PollCommand not implemented")
}
func (UnimplementedAgentServiceServer) GetBPFConfig(context.Context, *Empty) (*BPFConfig, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBPFConfig not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_ReportInterfaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportInterfacesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ReportInterfaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.AgentService/ReportInterfaces",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ReportInterfaces(ctx, req.(*ReportInterfacesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_SendPacketEvent_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentServiceServer).SendPacketEvent(&agentServiceSendPacketEventServer{stream})
}

type AgentService_SendPacketEventServer interface {
	SendAndClose(*Empty) error
	Recv() (*PacketEvent, error)
	grpc.ServerStream
}

type agentServiceSendPacketEventServer struct {
	grpc.ServerStream
}

func (x *agentServiceSendPacketEventServer) SendAndClose(m *Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *agentServiceSendPacketEventServer) Recv() (*PacketEvent, error) {
	m := new(PacketEvent)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _AgentService_PollCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).PollCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.AgentService/PollCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).PollCommand(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetBPFConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetBPFConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.AgentService/GetBPFConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetBPFConfig(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportInterfaces",
			Handler:    _AgentService_ReportInterfaces_Handler,
		},
		{
			MethodName: "PollCommand",
			Handler:    _AgentService_PollCommand_Handler,
		},
		{
			MethodName: "GetBPFConfig",
			Handler:    _AgentService_GetBPFConfig_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendPacketEvent",
			Handler:       _AgentService_SendPacketEvent_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "agent/agent.proto",
}
