// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: auth/auth.proto

package auth

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClaimsType int32

const (
	ClaimsType_UNSPECIFIED       ClaimsType = 0
	ClaimsType_ADMIN_UI_SESSION  ClaimsType = 1
	ClaimsType_API_AUTHORIZATION ClaimsType = 2
)

// Enum value maps for ClaimsType.
var (
	ClaimsType_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "ADMIN_UI_SESSION",
		2: "API_AUTHORIZATION",
	}
	ClaimsType_value = map[string]int32{
		"UNSPECIFIED":       0,
		"ADMIN_UI_SESSION":  1,
		"API_AUTHORIZATION": 2,
	}
)

func (x ClaimsType) Enum() *ClaimsType {
	p := new(ClaimsType)
	*p = x
	return p
}

func (x ClaimsType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClaimsType) Descriptor() protoreflect.EnumDescriptor {
	return file_auth_auth_proto_enumTypes[0].Descriptor()
}

func (ClaimsType) Type() protoreflect.EnumType {
	return &file_auth_auth_proto_enumTypes[0]
}

func (x ClaimsType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClaimsType.Descriptor instead.
func (ClaimsType) EnumDescriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{0}
}

type CredentialType int32

const (
	CredentialType_PASSWORD                CredentialType = 0
	CredentialType_EMAIL_VERIFICATION_CODE CredentialType = 1
)

// Enum value maps for CredentialType.
var (
	CredentialType_name = map[int32]string{
		0: "PASSWORD",
		1: "EMAIL_VERIFICATION_CODE",
	}
	CredentialType_value = map[string]int32{
		"PASSWORD":                0,
		"EMAIL_VERIFICATION_CODE": 1,
	}
)

func (x CredentialType) Enum() *CredentialType {
	p := new(CredentialType)
	*p = x
	return p
}

func (x CredentialType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CredentialType) Descriptor() protoreflect.EnumDescriptor {
	return file_auth_auth_proto_enumTypes[1].Descriptor()
}

func (CredentialType) Type() protoreflect.EnumType {
	return &file_auth_auth_proto_enumTypes[1]
}

func (x CredentialType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CredentialType.Descriptor instead.
func (CredentialType) EnumDescriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{1}
}

type IdentifierType int32

const (
	IdentifierType_ID    IdentifierType = 0
	IdentifierType_EMAIL IdentifierType = 1
)

// Enum value maps for IdentifierType.
var (
	IdentifierType_name = map[int32]string{
		0: "ID",
		1: "EMAIL",
	}
	IdentifierType_value = map[string]int32{
		"ID":    0,
		"EMAIL": 1,
	}
)

func (x IdentifierType) Enum() *IdentifierType {
	p := new(IdentifierType)
	*p = x
	return p
}

func (x IdentifierType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IdentifierType) Descriptor() protoreflect.EnumDescriptor {
	return file_auth_auth_proto_enumTypes[2].Descriptor()
}

func (IdentifierType) Type() protoreflect.EnumType {
	return &file_auth_auth_proto_enumTypes[2]
}

func (x IdentifierType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IdentifierType.Descriptor instead.
func (IdentifierType) EnumDescriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{2}
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_auth_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{0}
}

type ValidateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jwt           string                 `protobuf:"bytes,1,opt,name=jwt,proto3" json:"jwt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateSessionRequest) Reset() {
	*x = ValidateSessionRequest{}
	mi := &file_auth_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateSessionRequest) ProtoMessage() {}

func (x *ValidateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateSessionRequest.ProtoReflect.Descriptor instead.
func (*ValidateSessionRequest) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateSessionRequest) GetJwt() string {
	if x != nil {
		return x.Jwt
	}
	return ""
}

type ValidateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jwt           string                 `protobuf:"bytes,1,opt,name=jwt,proto3" json:"jwt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateSessionResponse) Reset() {
	*x = ValidateSessionResponse{}
	mi := &file_auth_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateSessionResponse) ProtoMessage() {}

func (x *ValidateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateSessionResponse.ProtoReflect.Descriptor instead.
func (*ValidateSessionResponse) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{2}
}

func (x *ValidateSessionResponse) GetJwt() string {
	if x != nil {
		return x.Jwt
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_auth_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{3}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AdministratorId     string                 `protobuf:"bytes,1,opt,name=administrator_id,json=administratorId,proto3" json:"administrator_id,omitempty"`
	OrganizationId      string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	AdministratorName   string                 `protobuf:"bytes,3,opt,name=administrator_name,json=administratorName,proto3" json:"administrator_name,omitempty"`
	OrganizationName    string                 `protobuf:"bytes,4,opt,name=organization_name,json=organizationName,proto3" json:"organization_name,omitempty"`
	BillingPlan         string                 `protobuf:"bytes,5,opt,name=billing_plan,json=billingPlan,proto3" json:"billing_plan,omitempty"`
	AdminUiAccessToken  string                 `protobuf:"bytes,6,opt,name=admin_ui_access_token,json=adminUiAccessToken,proto3" json:"admin_ui_access_token,omitempty"`
	AdminUiRefreshToken string                 `protobuf:"bytes,7,opt,name=admin_ui_refresh_token,json=adminUiRefreshToken,proto3" json:"admin_ui_refresh_token,omitempty"`
	ApiAccessToken      string                 `protobuf:"bytes,8,opt,name=api_access_token,json=apiAccessToken,proto3" json:"api_access_token,omitempty"`
	ApiRefreshToken     string                 `protobuf:"bytes,9,opt,name=api_refresh_token,json=apiRefreshToken,proto3" json:"api_refresh_token,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_auth_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{4}
}

func (x *LoginResponse) GetAdministratorId() string {
	if x != nil {
		return x.AdministratorId
	}
	return ""
}

func (x *LoginResponse) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *LoginResponse) GetAdministratorName() string {
	if x != nil {
		return x.AdministratorName
	}
	return ""
}

func (x *LoginResponse) GetOrganizationName() string {
	if x != nil {
		return x.OrganizationName
	}
	return ""
}

func (x *LoginResponse) GetBillingPlan() string {
	if x != nil {
		return x.BillingPlan
	}
	return ""
}

func (x *LoginResponse) GetAdminUiAccessToken() string {
	if x != nil {
		return x.AdminUiAccessToken
	}
	return ""
}

func (x *LoginResponse) GetAdminUiRefreshToken() string {
	if x != nil {
		return x.AdminUiRefreshToken
	}
	return ""
}

func (x *LoginResponse) GetApiAccessToken() string {
	if x != nil {
		return x.ApiAccessToken
	}
	return ""
}

func (x *LoginResponse) GetApiRefreshToken() string {
	if x != nil {
		return x.ApiRefreshToken
	}
	return ""
}

type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jwt           string                 `protobuf:"bytes,1,opt,name=jwt,proto3" json:"jwt,omitempty"`
	ClaimsType    ClaimsType             `protobuf:"varint,2,opt,name=claims_type,json=claimsType,proto3,enum=auth.ClaimsType" json:"claims_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_auth_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{5}
}

func (x *RefreshTokenRequest) GetJwt() string {
	if x != nil {
		return x.Jwt
	}
	return ""
}

func (x *RefreshTokenRequest) GetClaimsType() ClaimsType {
	if x != nil {
		return x.ClaimsType
	}
	return ClaimsType_UNSPECIFIED
}

type RefreshTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jwt           string                 `protobuf:"bytes,1,opt,name=jwt,proto3" json:"jwt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenResponse) Reset() {
	*x = RefreshTokenResponse{}
	mi := &file_auth_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResponse) ProtoMessage() {}

func (x *RefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{6}
}

func (x *RefreshTokenResponse) GetJwt() string {
	if x != nil {
		return x.Jwt
	}
	return ""
}

type CreateInstallKeyRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AdministratorEmail string                 `protobuf:"bytes,1,opt,name=administrator_email,json=administratorEmail,proto3" json:"administrator_email,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreateInstallKeyRequest) Reset() {
	*x = CreateInstallKeyRequest{}
	mi := &file_auth_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInstallKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInstallKeyRequest) ProtoMessage() {}

func (x *CreateInstallKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInstallKeyRequest.ProtoReflect.Descriptor instead.
func (*CreateInstallKeyRequest) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{7}
}

func (x *CreateInstallKeyRequest) GetAdministratorEmail() string {
	if x != nil {
		return x.AdministratorEmail
	}
	return ""
}

type CreateInstallKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstallKey    string                 `protobuf:"bytes,1,opt,name=install_key,json=installKey,proto3" json:"install_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInstallKeyResponse) Reset() {
	*x = CreateInstallKeyResponse{}
	mi := &file_auth_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInstallKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInstallKeyResponse) ProtoMessage() {}

func (x *CreateInstallKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInstallKeyResponse.ProtoReflect.Descriptor instead.
func (*CreateInstallKeyResponse) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{8}
}

func (x *CreateInstallKeyResponse) GetInstallKey() string {
	if x != nil {
		return x.InstallKey
	}
	return ""
}

type ResetVerifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetVerifyRequest) Reset() {
	*x = ResetVerifyRequest{}
	mi := &file_auth_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetVerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetVerifyRequest) ProtoMessage() {}

func (x *ResetVerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetVerifyRequest.ProtoReflect.Descriptor instead.
func (*ResetVerifyRequest) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{9}
}

func (x *ResetVerifyRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type ResetPasswordRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Credential         string                 `protobuf:"bytes,1,opt,name=credential,proto3" json:"credential,omitempty"`
	CredentialType     CredentialType         `protobuf:"varint,2,opt,name=credential_type,json=credentialType,proto3,enum=auth.CredentialType" json:"credential_type,omitempty"`
	Identifier         string                 `protobuf:"bytes,3,opt,name=identifier,proto3" json:"identifier,omitempty"`
	IdentifierType     IdentifierType         `protobuf:"varint,4,opt,name=identifier_type,json=identifierType,proto3,enum=auth.IdentifierType" json:"identifier_type,omitempty"`
	NewPassword        string                 `protobuf:"bytes,5,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	ConfirmNewPassword string                 `protobuf:"bytes,6,opt,name=confirm_new_password,json=confirmNewPassword,proto3" json:"confirm_new_password,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ResetPasswordRequest) Reset() {
	*x = ResetPasswordRequest{}
	mi := &file_auth_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordRequest) ProtoMessage() {}

func (x *ResetPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordRequest.ProtoReflect.Descriptor instead.
func (*ResetPasswordRequest) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{10}
}

func (x *ResetPasswordRequest) GetCredential() string {
	if x != nil {
		return x.Credential
	}
	return ""
}

func (x *ResetPasswordRequest) GetCredentialType() CredentialType {
	if x != nil {
		return x.CredentialType
	}
	return CredentialType_PASSWORD
}

func (x *ResetPasswordRequest) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *ResetPasswordRequest) GetIdentifierType() IdentifierType {
	if x != nil {
		return x.IdentifierType
	}
	return IdentifierType_ID
}

func (x *ResetPasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

func (x *ResetPasswordRequest) GetConfirmNewPassword() string {
	if x != nil {
		return x.ConfirmNewPassword
	}
	return ""
}

var File_auth_auth_proto protoreflect.FileDescriptor

const file_auth_auth_proto_rawDesc = "" +
	"\n" +
	"\x0fauth/auth.proto\x12\x04auth\x1a\x1cgoogle/api/annotations.proto\x1a\x15google/api/http.proto\"\a\n" +
	"\x05Empty\"*\n" +
	"\x16ValidateSessionRequest\x12\x10\n" +
	"\x03jwt\x18\x01 \x01(\tR\x03jwt\"+\n" +
	"\x17ValidateSessionResponse\x12\x10\n" +
	"\x03jwt\x18\x01 \x01(\tR\x03jwt\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\xa0\x03\n" +
	"\rLoginResponse\x12)\n" +
	"\x10administrator_id\x18\x01 \x01(\tR\x0fadministratorId\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12-\n" +
	"\x12administrator_name\x18\x03 \x01(\tR\x11administratorName\x12+\n" +
	"\x11organization_name\x18\x04 \x01(\tR\x10organizationName\x12!\n" +
	"\fbilling_plan\x18\x05 \x01(\tR\vbillingPlan\x121\n" +
	"\x15admin_ui_access_token\x18\x06 \x01(\tR\x12adminUiAccessToken\x123\n" +
	"\x16admin_ui_refresh_token\x18\a \x01(\tR\x13adminUiRefreshToken\x12(\n" +
	"\x10api_access_token\x18\b \x01(\tR\x0eapiAccessToken\x12*\n" +
	"\x11api_refresh_token\x18\t \x01(\tR\x0fapiRefreshToken\"Z\n" +
	"\x13RefreshTokenRequest\x12\x10\n" +
	"\x03jwt\x18\x01 \x01(\tR\x03jwt\x121\n" +
	"\vclaims_type\x18\x02 \x01(\x0e2\x10.auth.ClaimsTypeR\n" +
	"claimsType\"(\n" +
	"\x14RefreshTokenResponse\x12\x10\n" +
	"\x03jwt\x18\x01 \x01(\tR\x03jwt\"J\n" +
	"\x17CreateInstallKeyRequest\x12/\n" +
	"\x13administrator_email\x18\x01 \x01(\tR\x12administratorEmail\";\n" +
	"\x18CreateInstallKeyResponse\x12\x1f\n" +
	"\vinstall_key\x18\x01 \x01(\tR\n" +
	"installKey\"*\n" +
	"\x12ResetVerifyRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"\xa9\x02\n" +
	"\x14ResetPasswordRequest\x12\x1e\n" +
	"\n" +
	"credential\x18\x01 \x01(\tR\n" +
	"credential\x12=\n" +
	"\x0fcredential_type\x18\x02 \x01(\x0e2\x14.auth.CredentialTypeR\x0ecredentialType\x12\x1e\n" +
	"\n" +
	"identifier\x18\x03 \x01(\tR\n" +
	"identifier\x12=\n" +
	"\x0fidentifier_type\x18\x04 \x01(\x0e2\x14.auth.IdentifierTypeR\x0eidentifierType\x12!\n" +
	"\fnew_password\x18\x05 \x01(\tR\vnewPassword\x120\n" +
	"\x14confirm_new_password\x18\x06 \x01(\tR\x12confirmNewPassword*J\n" +
	"\n" +
	"ClaimsType\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10ADMIN_UI_SESSION\x10\x01\x12\x15\n" +
	"\x11API_AUTHORIZATION\x10\x02*;\n" +
	"\x0eCredentialType\x12\f\n" +
	"\bPASSWORD\x10\x00\x12\x1b\n" +
	"\x17EMAIL_VERIFICATION_CODE\x10\x01*#\n" +
	"\x0eIdentifierType\x12\x06\n" +
	"\x02ID\x10\x00\x12\t\n" +
	"\x05EMAIL\x10\x012\xb3\x04\n" +
	"\vAuthService\x12f\n" +
	"\x0fValidateSession\x12\x1c.auth.ValidateSessionRequest\x1a\x1d.auth.ValidateSessionResponse\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/v1/session\x12F\n" +
	"\x05Login\x12\x12.auth.LoginRequest\x1a\x13.auth.LoginResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/login\x12]\n" +
	"\fRefreshToken\x12\x19.auth.RefreshTokenRequest\x1a\x1a.auth.RefreshTokenResponse\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/v1/refresh\x12n\n" +
	"\x10CreateInstallKey\x12\x1d.auth.CreateInstallKeyRequest\x1a\x1e.auth.CreateInstallKeyResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/install-keys\x12Q\n" +
	"\vResetVerify\x12\x18.auth.ResetVerifyRequest\x1a\v.auth.Empty\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/reset-verify\x12R\n" +
	"\rResetPassword\x12\x1a.auth.ResetPasswordRequest\x1a\v.auth.Empty\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\x1a\r/v1/passwordsB?Z=github.com/danielhoward314/packet-sentry/protogen/golang/authb\x06proto3"

var (
	file_auth_auth_proto_rawDescOnce sync.Once
	file_auth_auth_proto_rawDescData []byte
)

func file_auth_auth_proto_rawDescGZIP() []byte {
	file_auth_auth_proto_rawDescOnce.Do(func() {
		file_auth_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_auth_proto_rawDesc), len(file_auth_auth_proto_rawDesc)))
	})
	return file_auth_auth_proto_rawDescData
}

var file_auth_auth_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_auth_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_auth_auth_proto_goTypes = []any{
	(ClaimsType)(0),                  // 0: auth.ClaimsType
	(CredentialType)(0),              // 1: auth.CredentialType
	(IdentifierType)(0),              // 2: auth.IdentifierType
	(*Empty)(nil),                    // 3: auth.Empty
	(*ValidateSessionRequest)(nil),   // 4: auth.ValidateSessionRequest
	(*ValidateSessionResponse)(nil),  // 5: auth.ValidateSessionResponse
	(*LoginRequest)(nil),             // 6: auth.LoginRequest
	(*LoginResponse)(nil),            // 7: auth.LoginResponse
	(*RefreshTokenRequest)(nil),      // 8: auth.RefreshTokenRequest
	(*RefreshTokenResponse)(nil),     // 9: auth.RefreshTokenResponse
	(*CreateInstallKeyRequest)(nil),  // 10: auth.CreateInstallKeyRequest
	(*CreateInstallKeyResponse)(nil), // 11: auth.CreateInstallKeyResponse
	(*ResetVerifyRequest)(nil),       // 12: auth.ResetVerifyRequest
	(*ResetPasswordRequest)(nil),     // 13: auth.ResetPasswordRequest
}
var file_auth_auth_proto_depIdxs = []int32{
	0,  // 0: auth.RefreshTokenRequest.claims_type:type_name -> auth.ClaimsType
	1,  // 1: auth.ResetPasswordRequest.credential_type:type_name -> auth.CredentialType
	2,  // 2: auth.ResetPasswordRequest.identifier_type:type_name -> auth.IdentifierType
	4,  // 3: auth.AuthService.ValidateSession:input_type -> auth.ValidateSessionRequest
	6,  // 4: auth.AuthService.Login:input_type -> auth.LoginRequest
	8,  // 5: auth.AuthService.RefreshToken:input_type -> auth.RefreshTokenRequest
	10, // 6: auth.AuthService.CreateInstallKey:input_type -> auth.CreateInstallKeyRequest
	12, // 7: auth.AuthService.ResetVerify:input_type -> auth.ResetVerifyRequest
	13, // 8: auth.AuthService.ResetPassword:input_type -> auth.ResetPasswordRequest
	5,  // 9: auth.AuthService.ValidateSession:output_type -> auth.ValidateSessionResponse
	7,  // 10: auth.AuthService.Login:output_type -> auth.LoginResponse
	9,  // 11: auth.AuthService.RefreshToken:output_type -> auth.RefreshTokenResponse
	11, // 12: auth.AuthService.CreateInstallKey:output_type -> auth.CreateInstallKeyResponse
	3,  // 13: auth.AuthService.ResetVerify:output_type -> auth.Empty
	3,  // 14: auth.AuthService.ResetPassword:output_type -> auth.Empty
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_auth_auth_proto_init() }
func file_auth_auth_proto_init() {
	if File_auth_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_auth_proto_rawDesc), len(file_auth_auth_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_auth_proto_goTypes,
		DependencyIndexes: file_auth_auth_proto_depIdxs,
		EnumInfos:         file_auth_auth_proto_enumTypes,
		MessageInfos:      file_auth_auth_proto_msgTypes,
	}.Build()
	File_auth_auth_proto = out.File
	file_auth_auth_proto_goTypes = nil
	file_auth_auth_proto_depIdxs = nil
}
