// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: accounts/accounts.proto

package accounts

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignupRequest struct {
	state                                 protoimpl.MessageState `protogen:"open.v1"`
	OrganizationName                      string                 `protobuf:"bytes,1,opt,name=organization_name,json=organizationName,proto3" json:"organization_name,omitempty"`
	PrimaryAdministratorEmail             string                 `protobuf:"bytes,2,opt,name=primary_administrator_email,json=primaryAdministratorEmail,proto3" json:"primary_administrator_email,omitempty"`
	PrimaryAdministratorName              string                 `protobuf:"bytes,3,opt,name=primary_administrator_name,json=primaryAdministratorName,proto3" json:"primary_administrator_name,omitempty"`
	PrimaryAdministratorCleartextPassword string                 `protobuf:"bytes,4,opt,name=primary_administrator_cleartext_password,json=primaryAdministratorCleartextPassword,proto3" json:"primary_administrator_cleartext_password,omitempty"`
	unknownFields                         protoimpl.UnknownFields
	sizeCache                             protoimpl.SizeCache
}

func (x *SignupRequest) Reset() {
	*x = SignupRequest{}
	mi := &file_accounts_accounts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignupRequest) ProtoMessage() {}

func (x *SignupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_accounts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignupRequest.ProtoReflect.Descriptor instead.
func (*SignupRequest) Descriptor() ([]byte, []int) {
	return file_accounts_accounts_proto_rawDescGZIP(), []int{0}
}

func (x *SignupRequest) GetOrganizationName() string {
	if x != nil {
		return x.OrganizationName
	}
	return ""
}

func (x *SignupRequest) GetPrimaryAdministratorEmail() string {
	if x != nil {
		return x.PrimaryAdministratorEmail
	}
	return ""
}

func (x *SignupRequest) GetPrimaryAdministratorName() string {
	if x != nil {
		return x.PrimaryAdministratorName
	}
	return ""
}

func (x *SignupRequest) GetPrimaryAdministratorCleartextPassword() string {
	if x != nil {
		return x.PrimaryAdministratorCleartextPassword
	}
	return ""
}

type SignupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignupResponse) Reset() {
	*x = SignupResponse{}
	mi := &file_accounts_accounts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignupResponse) ProtoMessage() {}

func (x *SignupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_accounts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignupResponse.ProtoReflect.Descriptor instead.
func (*SignupResponse) Descriptor() ([]byte, []int) {
	return file_accounts_accounts_proto_rawDescGZIP(), []int{1}
}

func (x *SignupResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type VerificationRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Token            string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	VerificationCode string                 `protobuf:"bytes,2,opt,name=verification_code,json=verificationCode,proto3" json:"verification_code,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *VerificationRequest) Reset() {
	*x = VerificationRequest{}
	mi := &file_accounts_accounts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificationRequest) ProtoMessage() {}

func (x *VerificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_accounts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificationRequest.ProtoReflect.Descriptor instead.
func (*VerificationRequest) Descriptor() ([]byte, []int) {
	return file_accounts_accounts_proto_rawDescGZIP(), []int{2}
}

func (x *VerificationRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *VerificationRequest) GetVerificationCode() string {
	if x != nil {
		return x.VerificationCode
	}
	return ""
}

type VerificationResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AdminUiAccessToken  string                 `protobuf:"bytes,1,opt,name=admin_ui_access_token,json=adminUiAccessToken,proto3" json:"admin_ui_access_token,omitempty"`
	AdminUiRefreshToken string                 `protobuf:"bytes,2,opt,name=admin_ui_refresh_token,json=adminUiRefreshToken,proto3" json:"admin_ui_refresh_token,omitempty"`
	ApiAccessToken      string                 `protobuf:"bytes,3,opt,name=api_access_token,json=apiAccessToken,proto3" json:"api_access_token,omitempty"`
	ApiRefreshToken     string                 `protobuf:"bytes,4,opt,name=api_refresh_token,json=apiRefreshToken,proto3" json:"api_refresh_token,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *VerificationResponse) Reset() {
	*x = VerificationResponse{}
	mi := &file_accounts_accounts_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificationResponse) ProtoMessage() {}

func (x *VerificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_accounts_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificationResponse.ProtoReflect.Descriptor instead.
func (*VerificationResponse) Descriptor() ([]byte, []int) {
	return file_accounts_accounts_proto_rawDescGZIP(), []int{3}
}

func (x *VerificationResponse) GetAdminUiAccessToken() string {
	if x != nil {
		return x.AdminUiAccessToken
	}
	return ""
}

func (x *VerificationResponse) GetAdminUiRefreshToken() string {
	if x != nil {
		return x.AdminUiRefreshToken
	}
	return ""
}

func (x *VerificationResponse) GetApiAccessToken() string {
	if x != nil {
		return x.ApiAccessToken
	}
	return ""
}

func (x *VerificationResponse) GetApiRefreshToken() string {
	if x != nil {
		return x.ApiRefreshToken
	}
	return ""
}

var File_accounts_accounts_proto protoreflect.FileDescriptor

const file_accounts_accounts_proto_rawDesc = "" +
	"\n" +
	"\x17accounts/accounts.proto\x12\baccounts\x1a\x1cgoogle/api/annotations.proto\x1a\x15google/api/http.proto\"\x93\x02\n" +
	"\rSignupRequest\x12+\n" +
	"\x11organization_name\x18\x01 \x01(\tR\x10organizationName\x12>\n" +
	"\x1bprimary_administrator_email\x18\x02 \x01(\tR\x19primaryAdministratorEmail\x12<\n" +
	"\x1aprimary_administrator_name\x18\x03 \x01(\tR\x18primaryAdministratorName\x12W\n" +
	"(primary_administrator_cleartext_password\x18\x04 \x01(\tR%primaryAdministratorCleartextPassword\"&\n" +
	"\x0eSignupResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"X\n" +
	"\x13VerificationRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12+\n" +
	"\x11verification_code\x18\x02 \x01(\tR\x10verificationCode\"\xd4\x01\n" +
	"\x14VerificationResponse\x121\n" +
	"\x15admin_ui_access_token\x18\x01 \x01(\tR\x12adminUiAccessToken\x123\n" +
	"\x16admin_ui_refresh_token\x18\x02 \x01(\tR\x13adminUiRefreshToken\x12(\n" +
	"\x10api_access_token\x18\x03 \x01(\tR\x0eapiAccessToken\x12*\n" +
	"\x11api_refresh_token\x18\x04 \x01(\tR\x0fapiRefreshToken2\xc5\x01\n" +
	"\x0fAccountsService\x12R\n" +
	"\x06Signup\x12\x17.accounts.SignupRequest\x1a\x18.accounts.SignupResponse\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v1/signup\x12^\n" +
	"\x06Verify\x12\x1d.accounts.VerificationRequest\x1a\x1e.accounts.VerificationResponse\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v1/verifyBCZAgithub.com/danielhoward314/packet-sentry/protogen/golang/accountsb\x06proto3"

var (
	file_accounts_accounts_proto_rawDescOnce sync.Once
	file_accounts_accounts_proto_rawDescData []byte
)

func file_accounts_accounts_proto_rawDescGZIP() []byte {
	file_accounts_accounts_proto_rawDescOnce.Do(func() {
		file_accounts_accounts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_accounts_accounts_proto_rawDesc), len(file_accounts_accounts_proto_rawDesc)))
	})
	return file_accounts_accounts_proto_rawDescData
}

var file_accounts_accounts_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_accounts_accounts_proto_goTypes = []any{
	(*SignupRequest)(nil),        // 0: accounts.SignupRequest
	(*SignupResponse)(nil),       // 1: accounts.SignupResponse
	(*VerificationRequest)(nil),  // 2: accounts.VerificationRequest
	(*VerificationResponse)(nil), // 3: accounts.VerificationResponse
}
var file_accounts_accounts_proto_depIdxs = []int32{
	0, // 0: accounts.AccountsService.Signup:input_type -> accounts.SignupRequest
	2, // 1: accounts.AccountsService.Verify:input_type -> accounts.VerificationRequest
	1, // 2: accounts.AccountsService.Signup:output_type -> accounts.SignupResponse
	3, // 3: accounts.AccountsService.Verify:output_type -> accounts.VerificationResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_accounts_accounts_proto_init() }
func file_accounts_accounts_proto_init() {
	if File_accounts_accounts_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_accounts_accounts_proto_rawDesc), len(file_accounts_accounts_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_accounts_accounts_proto_goTypes,
		DependencyIndexes: file_accounts_accounts_proto_depIdxs,
		MessageInfos:      file_accounts_accounts_proto_msgTypes,
	}.Build()
	File_accounts_accounts_proto = out.File
	file_accounts_accounts_proto_goTypes = nil
	file_accounts_accounts_proto_depIdxs = nil
}
