#!/usr/bin/env bash

set -euo pipefail

rm -rf certs/
mkdir certs

pushd certs

echo "Generating CA key and certificate..."

# Generate CA private key
openssl genrsa -out ca.key.pem 4096

# Generate self-signed CA certificate
openssl req -x509 -new -nodes -key ca.key.pem -sha256 -days 3650 \
  -subj "/CN=Packet Sentry CA" \
  -out ca.cert.pem

echo "Generating agent server key and certificate..."

# Generate agent server private key
openssl genrsa -out agent_server.key.pem 2048

# Generate agent server certificate signing request (dev hostname)
openssl req -new -key agent_server.key.pem -subj "/CN=agent-api.packet-sentry.local" -out agent_server.csr.pem

# Create a SAN config for the agent server certificate (dev hostname)
cat > agent_server_ext.cnf <<EOF
subjectAltName = DNS:agent-api.packet-sentry.local
EOF

# Self-sign the server certificate using the CA and add SAN
openssl x509 -req -in agent_server.csr.pem -CA ca.cert.pem -CAkey ca.key.pem \
  -CAcreateserial -out agent_server.cert.pem -days 365 -sha256 \
  -extfile agent_server_ext.cnf

# TODO: add other server certs for other services

echo "All certificates and keys generated:"
echo "- CA cert/key:                  ca.cert.pem / ca.key.pem"
echo "- Agent Server cert/key:        agent_server.cert.pem / agent_server.key.pem"

popd
