// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: events/events.proto

package events

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Start         string                 `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	End           string                 `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsRequest) Reset() {
	*x = GetEventsRequest{}
	mi := &file_events_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsRequest) ProtoMessage() {}

func (x *GetEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_events_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsRequest.ProtoReflect.Descriptor instead.
func (*GetEventsRequest) Descriptor() ([]byte, []int) {
	return file_events_events_proto_rawDescGZIP(), []int{0}
}

func (x *GetEventsRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *GetEventsRequest) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

func (x *GetEventsRequest) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

type Event struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EventTime      string                 `protobuf:"bytes,1,opt,name=event_time,json=eventTime,proto3" json:"event_time,omitempty"`
	Bpf            string                 `protobuf:"bytes,2,opt,name=bpf,proto3" json:"bpf,omitempty"`
	OriginalLength int32                  `protobuf:"varint,3,opt,name=original_length,json=originalLength,proto3" json:"original_length,omitempty"`
	IpSrc          string                 `protobuf:"bytes,4,opt,name=ip_src,json=ipSrc,proto3" json:"ip_src,omitempty"`
	IpDst          string                 `protobuf:"bytes,5,opt,name=ip_dst,json=ipDst,proto3" json:"ip_dst,omitempty"`
	TcpSrcPort     string                 `protobuf:"bytes,6,opt,name=tcp_src_port,json=tcpSrcPort,proto3" json:"tcp_src_port,omitempty"`
	TcpDstPort     string                 `protobuf:"bytes,7,opt,name=tcp_dst_port,json=tcpDstPort,proto3" json:"tcp_dst_port,omitempty"`
	IpVersion      string                 `protobuf:"bytes,8,opt,name=ip_version,json=ipVersion,proto3" json:"ip_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_events_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_events_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_events_events_proto_rawDescGZIP(), []int{1}
}

func (x *Event) GetEventTime() string {
	if x != nil {
		return x.EventTime
	}
	return ""
}

func (x *Event) GetBpf() string {
	if x != nil {
		return x.Bpf
	}
	return ""
}

func (x *Event) GetOriginalLength() int32 {
	if x != nil {
		return x.OriginalLength
	}
	return 0
}

func (x *Event) GetIpSrc() string {
	if x != nil {
		return x.IpSrc
	}
	return ""
}

func (x *Event) GetIpDst() string {
	if x != nil {
		return x.IpDst
	}
	return ""
}

func (x *Event) GetTcpSrcPort() string {
	if x != nil {
		return x.TcpSrcPort
	}
	return ""
}

func (x *Event) GetTcpDstPort() string {
	if x != nil {
		return x.TcpDstPort
	}
	return ""
}

func (x *Event) GetIpVersion() string {
	if x != nil {
		return x.IpVersion
	}
	return ""
}

type GetEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsResponse) Reset() {
	*x = GetEventsResponse{}
	mi := &file_events_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsResponse) ProtoMessage() {}

func (x *GetEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_events_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsResponse.ProtoReflect.Descriptor instead.
func (*GetEventsResponse) Descriptor() ([]byte, []int) {
	return file_events_events_proto_rawDescGZIP(), []int{2}
}

func (x *GetEventsResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

var File_events_events_proto protoreflect.FileDescriptor

const file_events_events_proto_rawDesc = "" +
	"\n" +
	"\x13events/events.proto\x12\x06events\x1a\x1cgoogle/api/annotations.proto\"W\n" +
	"\x10GetEventsRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x14\n" +
	"\x05start\x18\x02 \x01(\tR\x05start\x12\x10\n" +
	"\x03end\x18\x03 \x01(\tR\x03end\"\xf2\x01\n" +
	"\x05Event\x12\x1d\n" +
	"\n" +
	"event_time\x18\x01 \x01(\tR\teventTime\x12\x10\n" +
	"\x03bpf\x18\x02 \x01(\tR\x03bpf\x12'\n" +
	"\x0foriginal_length\x18\x03 \x01(\x05R\x0eoriginalLength\x12\x15\n" +
	"\x06ip_src\x18\x04 \x01(\tR\x05ipSrc\x12\x15\n" +
	"\x06ip_dst\x18\x05 \x01(\tR\x05ipDst\x12 \n" +
	"\ftcp_src_port\x18\x06 \x01(\tR\n" +
	"tcpSrcPort\x12 \n" +
	"\ftcp_dst_port\x18\a \x01(\tR\n" +
	"tcpDstPort\x12\x1d\n" +
	"\n" +
	"ip_version\x18\b \x01(\tR\tipVersion\":\n" +
	"\x11GetEventsResponse\x12%\n" +
	"\x06events\x18\x01 \x03(\v2\r.events.EventR\x06events2k\n" +
	"\rEventsService\x12Z\n" +
	"\x03Get\x12\x18.events.GetEventsRequest\x1a\x19.events.GetEventsResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/v1/events/{device_id}BAZ?github.com/danielhoward314/packet-sentry/protogen/golang/eventsb\x06proto3"

var (
	file_events_events_proto_rawDescOnce sync.Once
	file_events_events_proto_rawDescData []byte
)

func file_events_events_proto_rawDescGZIP() []byte {
	file_events_events_proto_rawDescOnce.Do(func() {
		file_events_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_events_events_proto_rawDesc), len(file_events_events_proto_rawDesc)))
	})
	return file_events_events_proto_rawDescData
}

var file_events_events_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_events_events_proto_goTypes = []any{
	(*GetEventsRequest)(nil),  // 0: events.GetEventsRequest
	(*Event)(nil),             // 1: events.Event
	(*GetEventsResponse)(nil), // 2: events.GetEventsResponse
}
var file_events_events_proto_depIdxs = []int32{
	1, // 0: events.GetEventsResponse.events:type_name -> events.Event
	0, // 1: events.EventsService.Get:input_type -> events.GetEventsRequest
	2, // 2: events.EventsService.Get:output_type -> events.GetEventsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_events_events_proto_init() }
func file_events_events_proto_init() {
	if File_events_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_events_events_proto_rawDesc), len(file_events_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_events_events_proto_goTypes,
		DependencyIndexes: file_events_events_proto_depIdxs,
		MessageInfos:      file_events_events_proto_msgTypes,
	}.Build()
	File_events_events_proto = out.File
	file_events_events_proto_goTypes = nil
	file_events_events_proto_depIdxs = nil
}
