name: Build, Test, Sign, and Upload packet-sentry

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, macos-latest, windows-latest]
        architecture: [amd64, arm64]
        # use exclude for non-sensical combinations
        exclude:
          - os: ubuntu-latest
            architecture: arm64
          - os: ubuntu-24.04-arm
            architecture: amd64
          - os: windows-latest
            architecture: arm64 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.24

      # Get values for cache paths to be used in later steps
      - name: Set Up Go Build Cache
        run: |
          echo "go-build=$(go env GOCACHE)" >> $GITHUB_ENV
          echo "go-mod=$(go env GOMODCACHE)" >> $GITHUB_ENV

      # Cache go build cache
      - name: Go Build Cache
        uses: actions/cache@v3
        with:
          path: ${{ env.go-build }}
          key: ${{ runner.os }}-${{ matrix.architecture }}-${{ github.ref_name }}-go-build-${{ hashFiles('**/go.sum') }}

      # Cache go mod cache
      - name: Go Mod Cache
        uses: actions/cache@v3
        with:
          path: ${{ env.go-mod }}
          key: ${{ runner.os }}-${{ matrix.architecture }}-${{ github.ref_name }}-go-mod-${{ hashFiles('**/go.sum') }}

      - name: Set up Go environment variables
        shell: bash
        run: |
          echo "GOARCH=${{ matrix.architecture }}" >> $GITHUB_ENV
          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            OS_NAME="linux"
          elif [ "${{ matrix.os }}" == "ubuntu-24.04-arm" ]; then
            OS_NAME="linux"
          elif [ "${{ matrix.os }}" == "macos-latest" ]; then
            OS_NAME="darwin"
          else
            OS_NAME="windows"
          fi
          echo "GOOS=${OS_NAME}" >> $GITHUB_ENV

      - name: Build Go Binary and Installer for ${{ matrix.os }} ${{ matrix.architecture }}
        shell: bash
        run: |
          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            echo "building Go binaries for linux amd64"
            ./scripts/build "linux" "amd64"
            echo "build Linux .deb installer for version 1.0.0 for amd64"
            go run ./linux-installer/main.go "1.0.0" "amd64"
            # TODO: linux installer validation
          elif [ "${{ matrix.os }}" == "ubuntu-24.04-arm" ]; then
            echo "building Go binaries for linux arm64"
            ./scripts/build "linux" "arm64"
            echo "build Linux .deb installer for version 1.0.0 for arm64"
            go run ./linux-installer/main.go "1.0.0" "arm64"
            # TODO: linux installer validation
          elif [ "${{ matrix.os }}" == "macos-latest" ]; then
            echo "building Go binaries for darwin ${{ matrix.architecture }}"
            ./scripts/build darwin "${{ matrix.architecture }}"
            # TODO: use git to get version
            echo "building macOS pkg installer for version 1.0.0 for ${{ matrix.architecture }}"
            ./macos-installer/build-installer.sh "1.0.0" "${{ matrix.architecture }}"
            echo "validating macOS pkg installer for version 1.0.0 for ${{ matrix.architecture }}"
            ./macos-installer/validate-installer.sh "1.0.0" "${{ matrix.architecture }}"
          else
            echo "building Go binaries for windows ${{ matrix.architecture }}"
            pwsh ./scripts/build.ps1 "${{ matrix.architecture }}"
            # TODO: use git to get version
            pwsh ./windows-installer/build-installer.ps1 -arch "${{ matrix.architecture }}" -version 1.0.0 -ci $true
            # TODO: windows installer validation
          fi